name: PyMarkdownLnt

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install PyMarkdownLnt
        run: |
          python -m pip install --upgrade pip
          pip install pymarkdownlnt

      - name: Lint Markdown files
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git ls-files --exclude-standard --cached --others -- '*.md' | xargs -I {} pymarkdown scan {}
